site_name: MovinThings
theme:
  name: readthedocs
nav:
  - "Home" : "index.md"
  - "Web Component" : "web_component.md"
  - "Backend" :
    - "Overview" : "backend_overview.md"
    - "API and data structures" : "backend_api_data.md"
    - "Behaviour" : "backend_behaviour.md"
  - "Starter project" : "starter.md"
markdown_extensions:
  - admonition
  - attr_list

